version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./.data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=trycore
      - MYSQL_USER=trycore
      - MYSQL_PASSWORD=trycore
    ports:
      - "3306:3306"